wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1665355609.711992
    t:
      1:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 54
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 54
      - 55
      - 80
      3:
      - 1
      - 16
      - 23
      4: 3.7.10
      5: 0.13.4
      8:
      - 1
      - 5
_wandb_kernel:
  desc: null
  value: aot
competition:
  desc: null
  value: RSNA_SpineFracture
